version: '3'
services:
  postgres:
    container_name: postgres-3d
    image: postgres:11.12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=inventory_management
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - web_nw

networks:
  web_nw:
    driver: bridge